# Generated by Django 2.2.12 on 2021-08-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tot',
            field=models.FloatField(default=0),
        ),
    ]
