# Generated by Django 2.2.12 on 2021-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_auto_20210820_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tot',
            field=models.IntegerField(default=0),
        ),
    ]
