# Generated by Django 2.2.12 on 2021-08-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_auto_20210820_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tot',
            field=models.IntegerField(default=1),
        ),
    ]
