# Generated by Django 2.2.12 on 2021-08-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0006_auto_20210820_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_birr',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Historypurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Customer')),
                ('items', models.ManyToManyField(to='supermarket.Product')),
            ],
        ),
    ]
